name: docker-stage
on:
  schedule:
    - cron: '0 1 * * 1'  # Every Monday at 1am
  push:
    branches:
      - "development"
permissions: read-all

jobs:
  build:
    name: Build ${{ matrix.service }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - { service: app, arch: linux/amd64, os: ubuntu-latest }
          - { service: app, arch: linux/arm64, os: ubuntu-24.04-arm }
          - { service: worker, arch: linux/amd64, os: ubuntu-latest }
          - { service: worker, arch: linux/arm64, os: ubuntu-24.04-arm }

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: development

      - name: Build image
        uses: unil-lettres/actions/docker-build@main
        with:
          dockerfile: ./docker/Dockerfile
          target: ${{ matrix.service }}-staging
          platform: ${{ matrix.arch }}
          image_repository: ${{ vars.DOCKERHUB_REPOSITORY }}
          name_prefix: ${{ matrix.service }}
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  merge-app:
    name: Merge app
    runs-on: ubuntu-latest
    needs: [build]
    outputs:
      tag: ${{ steps.merge.outputs.tag }}

    steps:
      - uses: actions/checkout@v5
        with:
          ref: development

      - name: Merge service
        id: merge
        uses: unil-lettres/actions/docker-merge-stage@main
        with:
          service: app
          image_repository: ${{ vars.DOCKERHUB_REPOSITORY }}
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  merge-worker:
    name: Merge worker
    runs-on: ubuntu-latest
    needs: [build]
    outputs:
      tag: ${{ steps.merge.outputs.tag }}

    steps:
      - uses: actions/checkout@v5
        with:
          ref: development

      - name: Merge service
        id: merge
        uses: unil-lettres/actions/docker-merge-stage@main
        with:
          service: worker
          image_repository: ${{ vars.DOCKERHUB_REPOSITORY }}
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  commit:
    name: Commit Image Tags
    runs-on: ubuntu-latest
    needs: [merge-app, merge-worker]

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: development

      - name: Update image
        uses: unil-lettres/actions/commit-version@main
        with:
          file_path: catima/values-stage.yaml
          versions: "${{ needs.merge-app.outputs.tag }}, ${{ needs.merge-worker.outputs.tag }}"
          version_keys: "app_image_tag, worker_image_tag"
          token: ${{ secrets.PAT_TOKEN }}
          repository: unil-lettres/k8s
          branch: main

  update-description:
    name: Update Description
    runs-on: ubuntu-latest
    needs: [merge-app, merge-worker]
    if: success()

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: development

      - name: Update description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ vars.DOCKERHUB_REPOSITORY }}
