name: docker-dev
on:
  push:
    branches:
      - "development"
permissions: read-all

jobs:
  build:
    name: Build ${{ matrix.service }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - { service: app, arch: linux/amd64, os: ubuntu-latest }
          - { service: app, arch: linux/arm64, os: ubuntu-24.04-arm }
          - { service: worker, arch: linux/amd64, os: ubuntu-latest }
          - { service: worker, arch: linux/arm64, os: ubuntu-24.04-arm }

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: development

      - name: Build image
        uses: unil-lettres/actions/docker-build@main
        with:
          dockerfile: ./docker/Dockerfile
          target: ${{ matrix.service }}-dev
          platform: ${{ matrix.arch }}
          image_repository: ${{ vars.DOCKERHUB_REPOSITORY }}
          name_prefix: ${{ matrix.service }}
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  merge:
    name: Merge ${{ matrix.service }}
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        service: [app, worker]

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: development

      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-${{ matrix.service }}-*
          merge-multiple: true

      - name: Merge digests into manifest
        uses: unil-lettres/actions/docker-merge@main
        with:
          image_repository: ${{ vars.DOCKERHUB_REPOSITORY }}
          tag: ${{ matrix.service }}-dev-latest
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  update-description:
    name: Update Description
    runs-on: ubuntu-latest
    needs: [merge]
    if: success()

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: development

      - name: Update description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ vars.DOCKERHUB_REPOSITORY }}
